import { useState, useRef } from "react";
import { MainLayout } from "@/components/layout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  FileUp, 
  FileText, 
  Loader2, 
  Download, 
  CheckCircle2, 
  AlertCircle,
  Sparkles,
  File,
  X
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface SummaryResult {
  eligibility: string[];
  benefits: string[];
  documents: string[];
  rawText?: string;
}

export default function SummarizerPage() {
  const [file, setFile] = useState<File | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [summary, setSummary] = useState<SummaryResult | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile) {
      if (selectedFile.type !== "application/pdf") {
        toast({
          title: "Invalid File Type",
          description: "Please upload a PDF document.",
          variant: "destructive",
        });
        return;
      }
      setFile(selectedFile);
      setSummary(null);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    const droppedFile = e.dataTransfer.files[0];
    if (droppedFile) {
      if (droppedFile.type !== "application/pdf") {
        toast({
          title: "Invalid File Type",
          description: "Please upload a PDF document.",
          variant: "destructive",
        });
        return;
      }
      setFile(droppedFile);
      setSummary(null);
    }
  };

  const handleProcess = async () => {
    if (!file) return;

    setIsProcessing(true);

    // Simulate processing - In production, this would call your API
    await new Promise(resolve => setTimeout(resolve, 3000));

    // Mock summary result
    const mockSummary: SummaryResult = {
      eligibility: [
        "Must be a citizen of India",
        "Annual household income below ₹2.5 Lakhs",
        "Age between 18-60 years",
        "Not availing similar benefits from other schemes",
      ],
      benefits: [
        "Health coverage up to ₹5 Lakhs per family per year",
        "Cashless treatment at empanelled hospitals",
        "Coverage for pre-existing diseases from day one",
        "No cap on family size or age",
      ],
      documents: [
        "Aadhaar Card (mandatory)",
        "Ration Card or BPL Certificate",
        "Income Certificate from competent authority",
        "Passport-size photographs",
        "Bank account details",
      ],
    };

    setSummary(mockSummary);
    setIsProcessing(false);

    toast({
      title: "Document Processed",
      description: "Your scheme document has been summarized successfully.",
    });
  };

  const handleDownload = () => {
    if (!summary) return;

    const text = `
SCHEME DOCUMENT SUMMARY
Generated by SchemesConnect

ELIGIBILITY CRITERIA
${summary.eligibility.map((item, i) => `${i + 1}. ${item}`).join("\n")}

BENEFITS
${summary.benefits.map((item, i) => `${i + 1}. ${item}`).join("\n")}

REQUIRED DOCUMENTS
${summary.documents.map((item, i) => `${i + 1}. ${item}`).join("\n")}

---
This summary was generated automatically. Please verify with official sources.
    `.trim();

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "scheme-summary.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const clearFile = () => {
    setFile(null);
    setSummary(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  return (
    <MainLayout>
      <div className="container py-8 md:py-12">
        {/* Header */}
        <div className="text-center mb-12">
          <Badge className="gov-badge mb-4">
            <Sparkles className="h-3 w-3" />
            AI-Powered
          </Badge>
          <h1 className="text-3xl md:text-4xl font-display font-bold mb-4">
            PDF Scheme Summarizer
          </h1>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Upload government scheme PDFs and get clear, structured summaries 
            of eligibility criteria, benefits, and required documents.
          </p>
        </div>

        <div className="max-w-4xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-8">
            {/* Upload Section */}
            <div className="space-y-6">
              <Card className="card-gradient">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <FileUp className="h-5 w-5 text-primary" />
                    Upload Document
                  </CardTitle>
                  <CardDescription>
                    Drag and drop a PDF or click to browse
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  {/* Drop Zone */}
                  <div
                    onDragOver={(e) => e.preventDefault()}
                    onDrop={handleDrop}
                    onClick={() => fileInputRef.current?.click()}
                    className="border-2 border-dashed border-border rounded-xl p-8 text-center cursor-pointer hover:border-primary/50 hover:bg-accent/30 transition-all"
                  >
                    <input
                      ref={fileInputRef}
                      type="file"
                      accept=".pdf"
                      onChange={handleFileSelect}
                      className="hidden"
                    />
                    
                    {!file ? (
                      <>
                        <div className="h-16 w-16 rounded-full bg-accent flex items-center justify-center mx-auto mb-4">
                          <FileText className="h-8 w-8 text-accent-foreground" />
                        </div>
                        <p className="font-medium mb-1">
                          Drop your PDF here
                        </p>
                        <p className="text-sm text-muted-foreground">
                          or click to browse files
                        </p>
                      </>
                    ) : (
                      <div className="flex items-center justify-between bg-secondary/50 rounded-lg p-4">
                        <div className="flex items-center gap-3">
                          <File className="h-8 w-8 text-primary" />
                          <div className="text-left">
                            <p className="font-medium text-sm">{file.name}</p>
                            <p className="text-xs text-muted-foreground">
                              {(file.size / 1024 / 1024).toFixed(2)} MB
                            </p>
                          </div>
                        </div>
                        <Button
                          variant="ghost"
                          size="icon-sm"
                          onClick={(e) => {
                            e.stopPropagation();
                            clearFile();
                          }}
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      </div>
                    )}
                  </div>

                  {/* Process Button */}
                  <Button
                    variant="hero"
                    className="w-full mt-4"
                    disabled={!file || isProcessing}
                    onClick={handleProcess}
                  >
                    {isProcessing ? (
                      <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        Processing...
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-4 w-4 mr-2" />
                        Summarize Document
                      </>
                    )}
                  </Button>
                </CardContent>
              </Card>

              {/* Tips */}
              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="text-sm flex items-center gap-2">
                    <AlertCircle className="h-4 w-4 text-primary" />
                    Tips for Best Results
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="text-sm text-muted-foreground space-y-2">
                    <li className="flex items-start gap-2">
                      <CheckCircle2 className="h-4 w-4 text-success mt-0.5 shrink-0" />
                      Upload official government scheme documents
                    </li>
                    <li className="flex items-start gap-2">
                      <CheckCircle2 className="h-4 w-4 text-success mt-0.5 shrink-0" />
                      Ensure the PDF is text-based, not scanned images
                    </li>
                    <li className="flex items-start gap-2">
                      <CheckCircle2 className="h-4 w-4 text-success mt-0.5 shrink-0" />
                      Documents in English work best
                    </li>
                  </ul>
                </CardContent>
              </Card>
            </div>

            {/* Summary Section */}
            <div>
              <Card className={`h-full ${summary ? "card-gradient" : ""}`}>
                <CardHeader>
                  <CardTitle className="flex items-center justify-between">
                    <span className="flex items-center gap-2">
                      <FileText className="h-5 w-5 text-primary" />
                      Document Summary
                    </span>
                    {summary && (
                      <Button variant="outline" size="sm" onClick={handleDownload}>
                        <Download className="h-4 w-4 mr-2" />
                        Download
                      </Button>
                    )}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  {!summary && !isProcessing && (
                    <div className="text-center py-12 text-muted-foreground">
                      <FileText className="h-12 w-12 mx-auto mb-4 opacity-30" />
                      <p>Upload a document to see the summary here</p>
                    </div>
                  )}

                  {isProcessing && (
                    <div className="text-center py-12">
                      <Loader2 className="h-12 w-12 mx-auto mb-4 animate-spin text-primary" />
                      <p className="font-medium">Analyzing document...</p>
                      <p className="text-sm text-muted-foreground mt-1">
                        This may take a few moments
                      </p>
                    </div>
                  )}

                  {summary && (
                    <div className="space-y-6 animate-fade-in">
                      {/* Eligibility */}
                      <div>
                        <h4 className="font-semibold text-sm text-primary mb-2 flex items-center gap-2">
                          <Badge variant="secondary" className="text-xs">Eligibility</Badge>
                        </h4>
                        <ul className="space-y-1.5">
                          {summary.eligibility.map((item, index) => (
                            <li key={index} className="flex items-start gap-2 text-sm">
                              <CheckCircle2 className="h-4 w-4 text-success mt-0.5 shrink-0" />
                              {item}
                            </li>
                          ))}
                        </ul>
                      </div>

                      {/* Benefits */}
                      <div>
                        <h4 className="font-semibold text-sm text-primary mb-2 flex items-center gap-2">
                          <Badge variant="secondary" className="text-xs">Benefits</Badge>
                        </h4>
                        <ul className="space-y-1.5">
                          {summary.benefits.map((item, index) => (
                            <li key={index} className="flex items-start gap-2 text-sm">
                              <Sparkles className="h-4 w-4 text-warning mt-0.5 shrink-0" />
                              {item}
                            </li>
                          ))}
                        </ul>
                      </div>

                      {/* Documents */}
                      <div>
                        <h4 className="font-semibold text-sm text-primary mb-2 flex items-center gap-2">
                          <Badge variant="secondary" className="text-xs">Required Documents</Badge>
                        </h4>
                        <ul className="space-y-1.5">
                          {summary.documents.map((item, index) => (
                            <li key={index} className="flex items-start gap-2 text-sm">
                              <FileText className="h-4 w-4 text-muted-foreground mt-0.5 shrink-0" />
                              {item}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </MainLayout>
  );
}
